import type { Equipment, Rental, Operator, Site, Alert, UsageAnalytics } from "@/types"

export const mockEquipment: Equipment[] = [
  {
    id: "EQU1001",
    type: "Excavator",
    model: "320D",
    serialNumber: "CAT320D001",
    status: "rented",
    location: {
      lat: 40.7128,
      lng: -74.006,
      address: "Construction Site A, New York",
    },
    specifications: {
      engineHours: 2847,
      fuelCapacity: 400,
      operatingWeight: 20500,
    },
  },
  {
    id: "EQU1002",
    type: "Crane",
    model: "M318F",
    serialNumber: "CAT318F002",
    status: "available",
    location: {
      lat: 40.7589,
      lng: -73.9851,
      address: "Equipment Yard, Manhattan",
    },
    specifications: {
      engineHours: 1523,
      fuelCapacity: 350,
      operatingWeight: 18200,
    },
  },
  {
    id: "EQU1003",
    type: "Bulldozer",
    model: "D6N",
    serialNumber: "CATD6N003",
    status: "rented",
    location: {
      lat: 40.6782,
      lng: -73.9442,
      address: "Brooklyn Infrastructure Project",
    },
    specifications: {
      engineHours: 3421,
      fuelCapacity: 450,
      operatingWeight: 19800,
    },
  },
  {
    id: "EQU1004",
    type: "Excavator",
    model: "336F",
    serialNumber: "CAT336F004",
    status: "overdue",
    location: {
      lat: 40.8176,
      lng: -73.9782,
      address: "Bronx Development Site",
    },
    specifications: {
      engineHours: 4156,
      fuelCapacity: 500,
      operatingWeight: 36200,
    },
  },
  {
    id: "EQU1005",
    type: "Bulldozer",
    model: "D8T",
    serialNumber: "CATD8T005",
    status: "rented",
    location: {
      lat: 40.5795,
      lng: -74.1502,
      address: "Staten Island Mining Operation",
    },
    specifications: {
      engineHours: 2103,
      fuelCapacity: 600,
      operatingWeight: 41500,
    },
  },
  {
    id: "EQU1006",
    type: "Grader",
    model: "140M",
    serialNumber: "CAT140M006",
    status: "maintenance",
    location: {
      lat: 40.7282,
      lng: -73.7949,
      address: "Queens Service Center",
    },
    specifications: {
      engineHours: 5234,
      fuelCapacity: 380,
      operatingWeight: 16800,
    },
  },
]

export const mockRentals: Rental[] = [
  {
    id: "REN001",
    equipmentId: "EQU1001",
    operatorId: "OP001",
    siteId: "SITE001",
    checkOutDate: "2025-01-15",
    checkInDate: null,
    plannedReturnDate: "2025-02-15",
    engineHoursStart: 2800,
    engineHoursEnd: null,
    fuelUsage: 145,
    operatingDays: 14,
    status: "active",
    qrCode: "QR_REN001_EQU1001",
  },
  {
    id: "REN002",
    equipmentId: "EQU1003",
    operatorId: "OP002",
    siteId: "SITE002",
    checkOutDate: "2025-01-10",
    checkInDate: null,
    plannedReturnDate: "2025-02-10",
    engineHoursStart: 3400,
    engineHoursEnd: null,
    fuelUsage: 89,
    operatingDays: 19,
    status: "active",
    qrCode: "QR_REN002_EQU1003",
  },
  {
    id: "REN003",
    equipmentId: "EQU1004",
    operatorId: "OP003",
    siteId: "SITE003",
    checkOutDate: "2024-12-20",
    checkInDate: null,
    plannedReturnDate: "2025-01-20",
    engineHoursStart: 4100,
    engineHoursEnd: null,
    fuelUsage: 234,
    operatingDays: 39,
    status: "overdue",
    qrCode: "QR_REN003_EQU1004",
  },
  {
    id: "REN004",
    equipmentId: "EQU1005",
    operatorId: "OP004",
    siteId: "SITE004",
    checkOutDate: "2025-01-25",
    checkInDate: null,
    plannedReturnDate: "2025-03-01",
    engineHoursStart: 2080,
    engineHoursEnd: null,
    fuelUsage: 67,
    operatingDays: 4,
    status: "active",
    qrCode: "QR_REN004_EQU1005",
  },
]

export const mockOperators: Operator[] = [
  {
    id: "OP001",
    name: "John Smith",
    email: "john.smith@construction.com",
    phone: "+1-555-0101",
    licenseNumber: "CDL-NY-12345",
    certifications: ["Heavy Equipment", "Excavator", "Safety Training"],
    activeRentals: 1,
  },
  {
    id: "OP002",
    name: "Maria Rodriguez",
    email: "maria.rodriguez@builders.com",
    phone: "+1-555-0102",
    licenseNumber: "CDL-NY-23456",
    certifications: ["Bulldozer", "Grader", "Advanced Safety"],
    activeRentals: 1,
  },
  {
    id: "OP003",
    name: "David Chen",
    email: "david.chen@infrastructure.com",
    phone: "+1-555-0103",
    licenseNumber: "CDL-NY-34567",
    certifications: ["Excavator", "Crane Operation", "Site Management"],
    activeRentals: 1,
  },
  {
    id: "OP004",
    name: "Sarah Johnson",
    email: "sarah.johnson@mining.com",
    phone: "+1-555-0104",
    licenseNumber: "CDL-NY-45678",
    certifications: ["Mining Equipment", "Bulldozer", "Environmental Safety"],
    activeRentals: 1,
  },
]

export const mockSites: Site[] = [
  {
    id: "SITE001",
    name: "Manhattan Tower Project",
    address: "123 Construction Ave, New York, NY",
    coordinates: { lat: 40.7128, lng: -74.006 },
    projectManager: "Robert Wilson",
    activeEquipment: 3,
  },
  {
    id: "SITE002",
    name: "Brooklyn Bridge Renovation",
    address: "456 Infrastructure Blvd, Brooklyn, NY",
    coordinates: { lat: 40.6782, lng: -73.9442 },
    projectManager: "Lisa Anderson",
    activeEquipment: 2,
  },
  {
    id: "SITE003",
    name: "Bronx Development Complex",
    address: "789 Development St, Bronx, NY",
    coordinates: { lat: 40.8176, lng: -73.9782 },
    projectManager: "Michael Brown",
    activeEquipment: 1,
  },
  {
    id: "SITE004",
    name: "Staten Island Mining Operation",
    address: "321 Mining Rd, Staten Island, NY",
    coordinates: { lat: 40.5795, lng: -74.1502 },
    projectManager: "Jennifer Davis",
    activeEquipment: 1,
  },
]

export const mockAlerts: Alert[] = [
  {
    id: "ALT001",
    type: "overdue",
    equipmentId: "EQU1004",
    message: "Equipment EQU1004 (Excavator 336F) is 9 days overdue for return",
    severity: "critical",
    timestamp: "2025-01-28T10:30:00Z",
    acknowledged: false,
  },
  {
    id: "ALT002",
    type: "maintenance",
    equipmentId: "EQU1006",
    message: "Grader 140M requires scheduled maintenance - 5000+ engine hours",
    severity: "high",
    timestamp: "2025-01-28T08:15:00Z",
    acknowledged: false,
  },
  {
    id: "ALT003",
    type: "idle_time",
    equipmentId: "EQU1001",
    message: "Excavator 320D has been idle for 6+ hours at current location",
    severity: "medium",
    timestamp: "2025-01-28T14:20:00Z",
    acknowledged: false,
  },
  {
    id: "ALT004",
    type: "fuel_low",
    equipmentId: "EQU1005",
    message: "Bulldozer D8T fuel level below 20% - refuel recommended",
    severity: "medium",
    timestamp: "2025-01-28T16:45:00Z",
    acknowledged: true,
  },
]

export const mockUsageAnalytics: UsageAnalytics[] = [
  {
    equipmentId: "EQU1001",
    totalHours: 47,
    idleHours: 8,
    fuelEfficiency: 3.2,
    utilizationRate: 83,
    maintenanceScore: 92,
  },
  {
    equipmentId: "EQU1003",
    totalHours: 21,
    idleHours: 2,
    fuelEfficiency: 4.1,
    utilizationRate: 90,
    maintenanceScore: 88,
  },
  {
    equipmentId: "EQU1004",
    totalHours: 56,
    idleHours: 15,
    fuelEfficiency: 2.8,
    utilizationRate: 73,
    maintenanceScore: 76,
  },
  {
    equipmentId: "EQU1005",
    totalHours: 23,
    idleHours: 1,
    fuelEfficiency: 3.8,
    utilizationRate: 96,
    maintenanceScore: 94,
  },
]
